file(READ "${TRACEABILITY_FILE}" TRACEABILITY_JSON)
string(JSON SCHEMA GET "${TRACEABILITY_JSON}" schema)
if(NOT SCHEMA EQUAL 1)
    message(FATAL_ERROR "Unsupported video traceability schema: ${SCHEMA}")
endif()

string(JSON REQUIREMENTS_LENGTH LENGTH "${TRACEABILITY_JSON}" requirements)
if(REQUIREMENTS_LENGTH LESS 1)
    message(FATAL_ERROR "Video traceability manifest is empty")
endif()

math(EXPR LAST_REQUIREMENT "${REQUIREMENTS_LENGTH} - 1")
set(IDS)
file(GLOB TEST_SOURCES "${TEST_SOURCE_DIR}/*.c" "${TEST_SOURCE_DIR}/*.cpp")
set(TEST_SOURCE_TEXT)
foreach(TEST_SOURCE IN LISTS TEST_SOURCES)
    file(READ "${TEST_SOURCE}" SOURCE_TEXT)
    string(APPEND TEST_SOURCE_TEXT "\n${SOURCE_TEXT}")
endforeach()

foreach(INDEX RANGE ${LAST_REQUIREMENT})
    string(JSON ID GET "${TRACEABILITY_JSON}" requirements ${INDEX} id)
    string(JSON TESTS_LENGTH LENGTH "${TRACEABILITY_JSON}" requirements ${INDEX} tests)
    if(TESTS_LENGTH LESS 1)
        message(FATAL_ERROR "${ID} has no mapped tests")
    endif()
    if(ID IN_LIST IDS)
        message(FATAL_ERROR "Duplicate video traceability ID: ${ID}")
    endif()
    string(FIND "${TEST_SOURCE_TEXT}" "${ID}" TEST_ID_OFFSET)
    if(TEST_ID_OFFSET EQUAL -1)
        message(FATAL_ERROR "${ID} is mapped but not present in a video test source")
    endif()
    list(APPEND IDS "${ID}")
endforeach()

string(REGEX MATCHALL "VID-[A-Z]+-[0-9]+" SOURCE_IDS "${TEST_SOURCE_TEXT}")
list(REMOVE_DUPLICATES SOURCE_IDS)
foreach(SOURCE_ID IN LISTS SOURCE_IDS)
    if(NOT SOURCE_ID IN_LIST IDS)
        message(FATAL_ERROR "${SOURCE_ID} is present in a video test source but missing from traceability")
    endif()
endforeach()
